# ---- Site Yapılandırması ----

# Tema.
theme: jekyll-theme-chirpy

# Github Pages kullanıyorsanız ve özel alan adına sahip değilseniz aşağıdaki
# değeri "/proje_adi" olarak değiştirin.
baseurl: '/blogum'

# Site dili. Dil dosyasını "_data/locales" klasörüne koyun, eğer eşleşen dosya
# bulunmazsa varsayılan (İngilizce - en) değerde çalışacaktır.
lang: tr-TR

# Tarih/saat yerelleştirmesi için opsiyonel bir değer.
prefer_datetime_locale: tr

# Saat dilimi.
timezone: Europe/Istanbul

# For SideBar
tagline-fsb: Yiğit'in Blogu

# jekyll-seo-tag ayarları.
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Blogum
tagline: Yiğit'in Blogu
description: >-
  Farklı konularda yazılar paylaşılan bir başka blog daha.
url: 'https://ygtadk.github.io'
github:
  username: ygtadk
  reponame: blogum
social:
  name: Yiğit Adak
  email: ygtadk100@gmail.com
  links:
    - https://github.com/ygtadk
    # İstediğiniz kadar bağlantı ekleyebilirsiniz.

google_site_verification: IMLLK3mDXPMeZ_BNkJ93aYmnBGKbbl5RaGO5V6YaVgQ

google_analytics:
  id: G-2Z3P50NFH3
  pv:
    proxy_endpoint:
    cache_path:

theme_mode: # Kalıcı olarak karanlık/aydınlık yapılabilir.

img_cdn:

# Avatar. Yan çubukta görünür.
avatar: assets/img/avatar.png

# TOC genel anahtarı.
toc: true

# Yorum sistemi ayarları.
comments:
  active:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:

paginate: 10

# Markdown için gelişmiş Ruby kütüphanesi.
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  subposts:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: false
      toc: true 
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

# Siteyi inşa ederken hariç tutulacak dosyalar/klasörler.
exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - LICENSE.md
  - LİSANS.md
  - gulpfile.js
  - node_modules
  - package*.json
  - Dockerfile

# jekyll-archives ayarları.
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]